
### Login
POST http://localhost:80/api/login
Content-Type: application/json

{
  "login": "Tester_#1",
  "password": "I_am_the_best"
}
> {%
    client.test("Login", function () {
        client.assert(response.status === 200, `Expected 200 but received '${response.status}'`)
        client.assert(response.body.token !== null
            && response.body.name !== null,
            `Expected jwt and name but didnt get it. Body: '${response.body}'`)
    })
    client.global.set("auth_token", response.body.token); %}

### Get user roles
GET http://localhost:80/api/user/roles
Content-Type: application/json
token: {{auth_token}}

> {% client.test('Get roles', function () {
    client.assert(response.status === 200, `Expected 200 but received '${response.status}'`);
    client.assert(response.body.includes("roles"), `Expected roles but didnt get proper json: '${response.body}'`)
    }) %}

### Get user available classes
GET http://localhost:80/api/user/classes
Content-Type: application/json
token: {{auth_token}}

> {% client.test('Get classes', function () {
        client.assert(response.status === 200, `Expected 200 but received '${response.status}'`);
        client.assert(response.body.includes("classes"), `Expected roles but didnt get proper json. Body: '${response.body}'`)
    })
    client.global.set('class_id', '300cf306-33c9-4bbc-996c-c5b2e03997ba') %}

### Get students list of class_id
GET http://localhost:80/api/user/classes/{{class_id}}/students
token: {{auth_token}}
Content-Type: application/json

> {% client.test('Get students of class', function () {
    client.assert(response.status === 200, `Expected 200 but received '${response.status}'`)
        client.assert(response.body.includes('students'), `Expected students object but received body: '${response.body}' `)
}) %}



###
PUT http://localhost:80/api/user/classes/{{class_id}}/students
token: {{auth_token}}
Content-Type: application/json

{
  "students": {
    "add": ["Ivanov1"],
    "remove": ["Ivanovov"]
  }
}

> {% client.test('Set students of class', function () {
        client.assert(response.status === 200, `Expected 200 but received '${response.status}'`);
    }) %}

### Insert data
PUT  http://localhost:80/api/user/classes/{{class_id}}/data
token: {{auth_token}}
Content-Type: application/json

{
  "absent_lists": {
    "ORVI": ["Ivanov"],
    "global": ["Ivanov", "Setkov", "Adminov"],
    "respectful": ["Adminov"],
    "fstudents": ["Setkov"]
  }
}

> {% client.test('Set students of class', function () {
        client.assert(response.status === 200, `Expected 200 but received '${response.status}'`);
    }) %}


### Get today's inserted data for class_id
GET http://localhost:80/api/user/classes/{{class_id}}/data
token: {{auth_token}}
Content-Type: application/json

> {% client.test('Get inserted data for today', function () {
        client.assert(response.status === 200, `Expected 200 but received '${response.status}'`)
        client.assert(response.body.includes('students'), `Expected students object but received body: '${response.body}' `)
    }) %}

### Get custom date inserted data for class_id
GET http://localhost:80/api/user/classes/{{class_id}}/data/2024-07-20
token: {{auth_token}}
Content-Type: application/json

> {% client.test('Get inserted data for custom date', function () {
        client.assert(response.status === 200, `Expected 200 but received '${response.status}'`)
        client.assert(response.body.includes('students'), `Expected students object but received body: '${response.body}' `)
    }) %}

###
# Region Admin - classes
### Get all classes
GET http://localhost:80/api/org/classes
token: {{auth_token}}

> {% client.test('Get all classes', function () {
        client.assert(response.status === 200, `Expected 200 but received '${response.status}'`);
    }) %}


### Get students of class
GET http://localhost:80/api/org/classes/{{class_id}}/students
token: {{auth_token}}

> {% client.test('Get students of class', function () {
        client.assert(response.status === 200, `Expected 200 but received '${response.status}'`);
    }) %}

### Create class
#POST http://localhost:80/api/org/classes
#token: {{auth_token}}
#Content-Type: application/json
#
#{
# "class_name": "Test class"
#}
#
## Create class with owner
#POST http://localhost:80/api/org/classes?withOwner=true
#token: {{auth_token}}
#Content-Type: application/json
#
#{
#  "class_name": "Test class",
#  "class_owner": "some id"
#}


### Rename class
#PATCH /api/org/classes/<id of class>
#
#{
#
#}


### Delete class
#DELETE /api/org/classes/<id of class>








### Get data for today
GET  http://localhost:80/api/org/data
token: {{auth_token}}

> {% client.test('Get data for today', function () {
        client.assert(response.status === 200, `Expected 200 but received '${response.status}'`);
    }) %}

### Get data for custom date
GET  http://localhost:80/api/org/data/2024-07-26
token: {{auth_token}}

> {% client.test('Get data for custom date', function () {
        client.assert(response.status === 200, `Expected 200 but received '${response.status}'`);
    }) %}


### Get summarized data
GET http://localhost:80/api/org/data-summary?startDate=2024-07-01&endDate=2024-07-28
token: {{auth_token}}

> {% client.test('Get summarized data', function () {
        client.assert(response.status === 200, `Expected 200 but received '${response.status}'`);
    }) %}

### Get list of all classes
GET http://localhost:80/api/org/classes
token: {{auth_token}}

> {% client.test('Get list of classes', function () {
        client.assert(response.status === 200, `Expected 200 but received '${response.status}'`);
    }) %}