POST http://localhost:80/api/login
Content-Type: application/json
#Accept: application/json
#Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MDk5MDUzNzEsImlzcyI6IkZsb2F0eUNvb2siLCJqdGkiOiIyMDI0LjMuOC4xMjUiLCJzdWIiOiJhZG1pblRva2VuIn0.HG2W-WQcObpsvghCGgbZZG5x6cZV2i6osehXuwHzt1M
#action: get
#method: customCase
#period: dateToDate
#schoolId: 125
#sasha - pwd
#Viktor - ???
#

{
  "login": "sasha",
  "password": "pwd"
}

> {%  client.global.set("token", response.body.token) %}
###
POST http://localhost:80/tempcheck

{
"token": {{token}}
}

###